### PR TITLE
[DO NOT MERGE] require routing-bundle not dev only

### PR DESCRIPTION
**Pull request by ElectricMaxxx**
#232 Described, why we should move the routing-bundle requirement from  dev to require.

### CODE REVIEW

**Comment by ElectricMaxxx** [comment]
Unfortunately this does not solve our issue. An existing routing-bundle and an enabled dynamic.router leads to an issue of a missing persistence configuration.

**Comment by dbu** [comment]
i would prefer to avoid this. can we avoid the dependency on the routing bundle? looking at the PublishWorkflow namespace or the publish-workflow.xml i see no reference to routing. where are we requiring it?

**Comment by dbu** [comment]
ah, found it. PublishWorkflowListener uses constants from the DynamicRouter. i will make that optional, thats a more lightweight change.

**Comment by ElectricMaxxx** [comment]
Making it optional is a BC problem, isn't it?

**Comment by ElectricMaxxx** [comment]
I'll close this, so lets discuss on #232

**Pull request closed without merging**
