### PR TITLE
DevKit updates

### PR DESCRIPTION
**Pull request by ElectricMaxxx**

### CODE REVIEW

**Comment by dbu** [comment]
seems to use the wrong version of symfony-cmf/testing, but the changes all look good to me.

**Comment by ElectricMaxxx** [comment]
@dbu no worries, for that reasons i created: https://github.com/symfony-cmf/core-bundle/pull/238

**Comment by ElectricMaxxx** [comment]
I think it it is a good practice for this first introduction: create dev-kit branch/PR and behind that the fixes to get it clean.

**Comment by ElectricMaxxx** [comment]
now we will see if it works :-)

**Pull request merged**
