### PR TITLE
upgrade to PHP8

### PR DESCRIPTION
**Pull request by jonasreymen**
| Q             | A
| ------------- | ---
| Branch?       | "master"
| Bug fix?      | yes
| New feature?  | yes
| BC breaks?    | yes
| Deprecations? | yes
| Fixed tickets | /
| License       | MIT
| Doc PR        | /

@dbu @esserj this PR is for upgrading core-bundle to support PHP8. 

You will see that SYMFONY_DEPRECATIONS_HELPER is changed to max[direct]=52 as we've tested it in Symfony 5.4, there are a lot of deprecations which should be fixed when upgrading to Symfony 6.0+, I have tried to battle these deprecations but It would require too much time to update these as they would require me to update a lot of sub dependencies/packages. I feel like these should not be fixed in the Symfony 5 upgrade

### CODE REVIEW

**Comment by esserj** [comment]
Hi @dbu,
I asked my colleague @jonasreymen to tackle the PHP8 upgrade.
If you have better suggestions for the deprecations issue let us know and we'll see what can be done.
allot of the deprecations already occurred when using symfony 5.1 (the first version supporting php 8)

**Review by dbu — APPROVED** [review]
thanks for the work. looks fine to me - and all changes are in the testing and not the src, so no risks included :+1: 

regarding symfony 6: yeah that one might necessite a new major version of the bundle to not have to worry about BC breaks.

i am not planning to work on that - but if you want to, please do.

**Comment by dbu** [comment]
hm, just had a look and the master branch (against which this PR went) already is preparing version 3 of the bundle. so BC breaks should be no worry.

if you need php 8 support urgently, we would need to create a branch from the latest 2.x release and backport the github actions build and this PR.

**Comment by esserj** [comment]
Hey @dbu,

We have a private packagist in which we have now applied these patches on a custom version. So it's not that urgent.
What are the things that still need to happen for a 3 release? Maybe we can find the time to assist.

**Comment by dbu** [comment]
it would be great if you want to do some things. i created some issues for what i think is necessary for version 3:

https://github.com/symfony-cmf/core-bundle/milestone/7

**Pull request merged**
