### PR TITLE
Add support for symfony 5

### PR DESCRIPTION
**Pull request by esserj**
| Q             | A
| ------------- | ---
| Branch?       | "master" for new features / the branch of the current release for fixes
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Fixed tickets | none
| License       | MIT
| Doc PR        | reference to the documentation PR, if any

### CODE REVIEW

**Comment by esserj** [comment]
Hi @dbu,

I've tried my best keeping compatibility with older doctrine/symfony, not sure how long you still wanted to maintain that BC.
Hope you have time to look into this PR.

Thanks in advance for you time!

Regards @esserj

**Comment by dbu** [comment]
thanks. the CI setup is quite outdated on the repository. i am trying to get it to build again in #276. i dropped lots of old versions already.

however, i needed to do some changes to make the build succeed. dependencies of this bundle are all very "optional" and therefore not well defined. i wonder if we should make the upgrade a new major release. that could then also make this PR not have to worry about the BC edge cases...

**Comment by dbu** [comment]
@esserj what do you think if we do a version 3 of this bundle that supports symfony 4.4, 5.4 and 6 that does BC breaks as necessary?

**Comment by esserj** [comment]
hi @dbu seems ok to me, I can update the PR of that is where you'd like to head to, and remove some of the existing BC

**Comment by dbu** [comment]
great! i merged the changes to master, can you please rebase this branch? and then add the new symfony version to the github action so we see if it works?

**Comment by esserj** [comment]
will do @dbu later today

**Comment by esserj** [comment]
@dbu just to be sure, just rebase as is right? or do you want me to change it already to >=4.4

**Comment by esserj** [comment]
oh wait my bad didnt look at master 🤦

**Comment by dbu** [comment]
i changed master to symfony 4.4 and php 7.4 because i could not get the CI to work with older versions easily, and found it not worth it to fix the CI setup for obsolete versions after we did not touch the repository for 2 years ;-)

so when you rebase, you probably get conflicts, as we need everything to be Symfony ^4.4 || ^5 and php 7.4. we can then also add PHP 8 to the build matrix, but in another PR.

**Comment by esserj** [comment]
I'll let the workflow run first without to much BC removal, will remove what I come across after a first successful run

**Comment by esserj** [comment]
Hi @dbu ,

I notices deprecations for symfony2 in
`\Symfony\Cmf\Bundle\CoreBundle\PublishWorkflow\Voter\PublishableVoter`
and
`\Symfony\Cmf\Bundle\CoreBundle\PublishWorkflow\Voter\PublishTimePeriodVoter`

I assume they have to do with the New voter class in Symfony and how the `Decision Strategy` can be configured, So I made the changes as I thought they should be now, especially the unsupported attribute which will now be: at least one supported attribute

I also found `Symfony\Cmf\Bundle\CoreBundle\Security\Authorization\Voter\PublishedVoter` bit I can't really find what it is still used for.

  <service id="cmf_core.security.published_voter" class="Symfony\Cmf\Bundle\CoreBundle\PublishWorkflow\Voter\PublishableVoter" public="false">
            <tag name="security.voter"/>
        </service>

seems to be the security voter is this a mistake and should `Symfony\Cmf\Bundle\CoreBundle\Security\Authorization\Voter\PublishedVoter` be the security voter instead?
If i read the (deprecated) core bundle docs https://github.com/symfony-cmf/symfony-cmf-docs/blob/master/bundles/core/publish_workflow.rst they seem to imply Symfony\Cmf\Bundle\CoreBundle\Security\Authorization\Voter\PublishedVoter is used?

**Review by dbu — APPROVED** [review]
thanks. this looks right to me, so i'll merge.

we can do further cleanups in separate MRs.

**Comment by dbu** [comment]
> voters

its been a very long time :see_no_evil: i actually don't remember, and it was all done for symfony 2, so maybe during the upgrades and refactorings something ended up wrong.

you are right that we deprecated the docs (and also many of the cmf bundles). the only actively maintained thing is the cmf routing component & bundle. we should check which parts of the core bundle are still important to maintain and only keep those. and move the docs for that part to https://github.com/symfony-cmf/routing-docs - that is what is rendered at https://symfony.com/bundles/CMFRoutingBundle/current/index.html

**Comment by esserj** [comment]
Yeah, We are actually only using the publishable workflow from core, doesnt seem like the twig extensions cause much of a maintenance burden though.

when I was looking through the history of the workflow services file, I notices that the security voter class was defined as a class param (as was done back in the day) but was never actually used, so I do think it was a mistake, but probably not a very important one, bacause I think the main use of the workflow is through the request listener, and not through the security component

**Comment by dbu** [comment]
ah, now that you say this: i think one use case was to decide on a route object if the current user is allowed to see it, to decide whether to render the url (in a menu or such). could the extra voter be for that?

**Comment by esserj** [comment]
Not sure, seems to me that you'd do that with the workflow, the security voter is more the generic way of symfony to do access control

https://symfony.com/doc/2.6/cookbook/security/voters.html#declaring-the-voter-as-a-service
and the `denyAccessUnlessGranted` controller method (similar to using the workflow checker) but I thought the workflow checker was smart enough not to start a session

**Pull request merged**
